blank_issues_enabled: true
contact_links:
  - name: XDA Developers
    url: https://forum.xda-developers.com/t/app-xposed-magisk-knoxpatch-v0-6-1-restore-samsung-knox-features.4549179/
    about: Find support in the official project thread.
